version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    MONGODB_URI: ${{secrets.MONGODB_URI}}
    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
